# Generated by Django 6.0.5 on 2026-05-16 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_description', models.TextField()),
                ('quantity', models.CharField(help_text="e.g., 'Serves 50 people' or '10 kg'", max_length=100)),
                ('preparation_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='donation_images/')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ACCEPTED', 'Accepted by NGO'), ('ASSIGNED', 'Assigned to Volunteer'), ('PICKED_UP', 'Picked Up'), ('DELIVERED', 'Delivered')], default='AVAILABLE', max_length=20)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations_made', to=settings.AUTH_USER_MODEL)),
                ('ngo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_accepted', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_assigned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
